clue/reactphp-sqlite

src/Database.php
tests/FunctionalDatabaseTest.php

This somewhat obscure PR ensures that we do not inherit open file
descriptors (FDs) to the SQLite child worker process. This can cause all
sorts of errors in long running applications and really is not desired
here.
This is implemented by explicitly overwriting all superfluous FDs with
dummy file handles and then closing all of these in the implicit `sh`
child process before launching the actual php binary. PHP does not
support `FD_CLOEXEC`, `O_CLOEXEC` or `SOCK_CLOEXEC`  and this appears to
be the best work around I could find (yes, I should probably write a
lengthy, somewhat technical blog post about this). Additionally, this PR
includes a test to verify this works on all supported platforms and this
could perhaps be used as a starting point for other libraries (YMMV).
This builds on …

Do not inherit open FDs to SQLite worker by overwriting and closing

---

README.md
examples/insert.php
examples/search.php
src/Database.php
src/DatabaseInterface.php
src/Factory.php
src/Io/ProcessIoDatabase.php
tests/FunctionalDatabaseTest.php
tests/Io/DatabaseTest.php

This is done to achieve better separation of concerns in preparation for creating multiple database launchers and database communication implementations for Windows support in the future.
Refs #3

Refactor to use dedicated `Factory` to open database and split `DatabaseInterface` and internal `ProcessIoDatabase` implementation

---

.travis.yml
README.md
res/sqlite-worker.php
src/Factory.php
src/Io/ProcessIoDatabase.php
tests/FunctionalDatabaseTest.php

Resolves #3 
Builds on top of #12 
Refs https://github.com/reactphp/child-process/pull/67
Refs https://github.com/reactphp/child-process/pull/71

Support Windows by using temporary network socket for process I/O 

---

tests/FunctionalDatabaseTest.php

There's a very short race condition where the forked php process first
has to `dup()` the file descriptor specs before invoking `exec()` to
switch to the actual `ssh` child process. We don't need to wait for the
child process to be ready, but only for the forked process to close the
file descriptors. This happens ~80% of times on single core machines and
almost never on multi core systems, so simply wait 5ms (plenty of time!)
and retry again.
Builds on top of #7

Avoid race condition for forked process in test suite

---

README.md
res/sqlite-worker.php
src/DatabaseInterface.php
src/Io/ProcessIoDatabase.php
tests/FunctionalDatabaseTest.php

Support type mapping for float and boolean values

---

README.md
res/sqlite-worker.php
src/DatabaseInterface.php
src/Io/ProcessIoDatabase.php
tests/FunctionalDatabaseTest.php

Resolves #4 
Builds on top of #14

Encode valid UTF-8 strings as TEXT and binary strings as BLOB

---

README.md
res/sqlite-worker.php
src/DatabaseInterface.php
src/Io/ProcessIoDatabase.php
tests/FunctionalDatabaseTest.php

Support float values without fraction on legacy PHP < 5.6.6

---

.travis.yml
README.md

Refs https://github.com/reactphp/cache/pull/36

Drop support for HHVM, HHVM does not support PHP anymore

---

res/sqlite-worker.php
tests/FunctionalDatabaseTest.php

Trying to fetch a result set row for a query that returns an empty
result set results in the query being executed again. We avoid this by
first checking if there are any columns and avoid fetch result rows
otherwise.

Fix selecting empty result sets and avoid implicitly executing twice

---

src/Factory.php

Try to look up php binary for child worker process when running from
php-cgi binary. Additionally, chdir() to child worker source folder when
spawning child to avoid lengthy command line (ps output).

Support executing from CGI binary and simplify child command line (ps)

---

README.md
examples/insert.php
examples/search.php
src/Factory.php
src/Io/LazyDatabase.php
tests/FactoryTest.php
tests/Io/LazyDatabaseTest.php
tests/Io/ProcessIoDatabaseTest.php

Builds on top of clue/reactphp-redis#87 and friends-of-reactphp/mysql#87 and others.
Resolves #2

Add new `loadLazy()` method to connect only on demand and implement "idle" timeout to close underlying connection when unused.

---

README.md
src/Factory.php
tests/FactoryTest.php

Resolve relative paths to SQLite database files in Factory

---

res/sqlite-worker.php
src/Io/ProcessIoDatabase.php
tests/FunctionalDatabaseTest.php

The result set for DDL queries (INSERT, UPDATE, DELETE etc.) is empty,
i.e. it does not contain any columns or rows. Columns and rows should
thus be represented by a null value. In contrast, an empty result set
from a SELECT query will always contain a non-empty array of columns and
may contain any number of rows (possibly an empty array of rows).
Builds on top of #20

Fix result set rows for DDL queries to be null, instead of empty array

---

README.md
composer.json
examples/insert.php
examples/search.php
src/Factory.php

This changeset simplifies usage by supporting the new [default loop](https://github.com/reactphp/event-loop#loop).
```php
// old (still supported)
$factory = new Clue\React\SQLite\Factory($loop);
// new (using default loop)
$factory = new Clue\React\SQLite\Factory();
```
Builds on top of https://github.com/reactphp/event-loop/pull/226, https://github.com/reactphp/event-loop/pull/229 and https://github.com/reactphp/event-loop/pull/232

Simplify usage by supporting new default loop

---

res/sqlite-worker.php
tests/FunctionalDatabaseTest.php

When writing a null byte inside your file path to your SQLite database it's possible to receive an `TypeError` (for PHP >= 7) in return.
For older PHP versions we're already handling the thrown `Exception`.

Reject null byte in path to SQLite database file

---

README.md
examples/insert.php
examples/search.php

Just fixed some typos and improved the `README` and examples.

Improve documentation and examples

---

src/Factory.php
tests/FunctionalFactoryTest.php

Fail fast without waiting for timeout if process dies while connecting

---

README.md
res/sqlite-worker.php
src/Factory.php
src/Io/BlockingDatabase.php
tests/FunctionalDatabaseTest.php
tests/Io/BlockingDatabaseTest.php

This changeset adds support for using a blocking SQLite adapter when using an empty binary path.
Using an empty parameter to pass an empty PHP binary path will now cause this project to not spawn a PHP child process for any database interactions at all. In this case, using SQLite will block the main process, but continues to provide the exact same async API. This can be useful if concurrent execution is not needed, especially when running behind a traditional web server (non-CLI SAPI).
```php
// advanced usage: empty binary path runs blocking SQLite in same process
$factory = new Clue\React\SQLite\Factory(null, '');
```
Builds on top of #45
Refs #35

Support using blocking SQLite adapter when using an empty binary path

---

.gitignore
README.md
examples/insert.php
examples/query.php
examples/search.php
src/Factory.php
tests/FunctionalExampleTest.php

This changeset ensures we use the default `php` binary instead of respecting `PHP_BINARY` when automatic binary detection fails for non-CLI SAPIs. This ensure we never try to execute a `php-cgi` binary when running behind CGI when the executable uses a custom name or [`open_basedir`](https://www.php.net/manual/en/ini.core.php#ini.open-basedir) restrictions are in effect.
The implementation is pretty straight forward, but significant effort went into making sure this works across the variety of supported platforms and is tested appropriately. You're looking at close to two days worth of testing alone, enjoy!
Builds on top of #48 and #45
Builds on top of #7 
Refs #35

Use default `php` binary instead of respecting `PHP_BINARY` when automatic binary detection fails for non-CLI SAPIs

---

.github/workflows/ci.yml
README.md
src/Factory.php

This changeset adds support for the upcoming PHP 8.1 version. Builds on top of #37.

Support PHP 8.1 and minor clean up

---

.github/workflows/ci.yml
phpunit.xml.dist
phpunit.xml.legacy
src/Factory.php
tests/install-as-dep/.gitignore
tests/install-as-dep/composer.json
tests/install-as-dep/query.php

This changeset adds support for running from PHARs. This works out of the box without any special configuration by running the SQLite worker like this internally:
```php
$ php -r 'require("phar:///home/alice/Desktop/acme.phar/vendor/clue/reactphp-sqlite/res/sqlite-worker.php");'
```
The updated test suite confirms this works across all supported platforms, including Windows (which requires some special care). Windows tests on PHP < 7.3 may currently be skipped because building the PHAR fails due to https://github.com/clue/phar-composer/issues/116, but execution should work just fine in either case.
Resolves / closes #5
Builds on top of #50, #45, https://github.com/clue/phar-composer/pull/123 and others

Support running from PHAR

---

res/sqlite-worker.php
src/Io/ProcessIoDatabase.php

Simplify internal JSON-RPC protocol by avoiding unneeded escapes

---

.github/workflows/ci.yml
tests/install-as-dep/composer.json

The updated test suite now confirms executing from a PHP archives (PHAR) works across all supported platforms, including Windows (which requires some special care).
Builds on top of #55, https://github.com/clue/phar-composer/pull/129, https://github.com/clue/phar-composer/pull/130, and referenced tickets
Builds on top of #13 and #55 for special Windows support
Refs #5 for improved PHAR support

Update test suite & clue/phar-composer to avoid skipped tests on Windows
